using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;

namespace Plugin.Games
{

#region Shared

    /// <summary>
    /// Platform type used to indicate which gaming platform the authentication response is from
    /// </summary>
    public enum GamesAuthPlatform
    {
        /// <summary>
        /// (Android Only) Google Play Games Services
        /// </summary>
        Android,
        /// <summary>
        /// (Apple Only) Apple Games Center
        /// </summary>
        Apple
    }

    /// <summary>
    /// Represents the response received when requesting a server-side authentication for the signed-in player.
    /// </summary>
    public sealed class GamesAuthResponse
    {
        /// <summary>
        /// The platform the authentication response is from.
        /// </summary>
        public GamesAuthPlatform Platform { get; }

#if ANDROID
        /// <summary>
        /// (Android Only) The response from Google Play Games Services
        /// </summary>
        public GamesAuthResponseAndroid Android { get; }
#elif IOS || MACCATALYST
        /// <summary>
        /// (Apple Only) The response from Apple Games Center
        /// </summary>
        public GamesAuthResponseApple Apple { get; }
#endif

        internal GamesAuthResponse(GamesAuthPlatform platform, GamesAuthResponseAndroid android = null, GamesAuthResponseApple apple = null)
        {
            Platform = platform;
#if ANDROID
            Android = android;
#elif IOS || MACCATALYST
            Apple = apple;
#endif
        }

        internal static GamesAuthResponse FromAndroid(GamesAuthResponseAndroid android)
            => new(GamesAuthPlatform.Android, android: android);

        internal static GamesAuthResponse FromApple(GamesAuthResponseApple apple)
            => new(GamesAuthPlatform.Apple, apple: apple);
    }

#endregion

#region Apple

    /// <summary>
    /// (Apple Only) Capability type used to indicate unavailable features in the games SDK of the current platform
    /// </summary>
    public enum GamesCapability
    {
        /// <summary>
        /// Multiplayer gaming is restricted
        /// </summary>
        Multiplayer,

        /// <summary>
        /// In-game communication is restricted
        /// </summary>
        InGameCommunication,

        /// <summary>
        /// Explicit content is restricted
        /// </summary>
        ExplicitContent
    }

    /// <summary>
    /// Represents the response received from Apple Game Center when requesting a server-side authentication for the signed-in player.
    /// </summary>
    public sealed class GamesAuthResponseApple
    {
        /// <summary>
        /// The URL for the public key used to verify the identity of the player.
        /// </summary>
        public Uri PublicKeyUrl { get; }

        /// <summary>
        /// The signature data generated by Apple to verify the identity of the player.
        /// </summary>
        public byte[] Signature { get; }

        /// <summary>
        /// The salt data used to verify the identity of the player.
        /// </summary>
        public byte[] Salt { get; }

        /// <summary>
        /// The timestamp used to verify the identity of the player.
        /// </summary>
        public ulong Timestamp { get; }

        internal GamesAuthResponseApple(Uri publicKeyUrl, byte[] signature, byte[] salt, ulong timestamp)
        {
            PublicKeyUrl = publicKeyUrl;
            Signature = signature;
            Salt = salt;
            Timestamp = timestamp;
        }
    }

#endregion

#region Android

    /// <summary>
    /// Scope type used to authenticate with the games SDK of the current platform
    /// </summary>
    public enum GamesAuthScope
    {
        //Android Google Play Games Scopes
        /// <summary>
        /// OAuth 2.0 Scope used to authenticate the backend server with the games SDK.
        /// </summary>
        Email,
        /// <summary>
        /// OAuth 2.0 Scope used to authenticate the backend server with the games SDK.
        /// </summary>
        OpenId,
        /// <summary>
        /// OAuth 2.0 Scope used to authenticate the backend server with the games SDK.
        /// </summary>
        Profile,

        /// <summary>
        /// An unknown type, possibly recently added in a new update.
        /// </summary>
        Unknown = -1
    }

    /// <summary>
    /// Represents the response received from Play Games Services when requesting a server-side OAuth 2.0 authorization code for the signed-in player.
    /// This response provides credentials and information intended for your server to enable server-side interaction with Play Games Services web APIs on behalf of the player.It includes:
    /// OAuth 2.0 authorization code: A short-lived credential to be sent securely to your server.Your server can exchange this code for access and refresh tokens, enabling server-side API calls.
    /// list of granted scopes: A list of the AuthScope permissions the user explicitly granted consent for (or previously approved). The list will be empty if the user declines consent and none of the requested AuthScope were previously granted.
    /// </summary>
    public class GamesAuthResponseAndroid : IEquatable<GamesAuthResponseAndroid>
    {
        /// <summary>
        /// OAuth 2.0 authorization code to be sent securely to your backend server.
        /// </summary>
        public string AuthorizationCode { get; }

        /// <summary>
        /// OAuth 2.0 permissions that were explicitly granted by the user.
        /// May be empty if the user declined consent.
        /// </summary>
        public IReadOnlyList<GamesAuthScope> GrantedScopes { get; }

        internal GamesAuthResponseAndroid(string authorizationCode, IEnumerable<GamesAuthScope> grantedScopes)
        {
            AuthorizationCode = authorizationCode
                ?? throw new ArgumentNullException(nameof(authorizationCode));

            if (grantedScopes == null)
                throw new ArgumentNullException(nameof(grantedScopes));

            GrantedScopes = new ReadOnlyCollection<GamesAuthScope>(
                grantedScopes.ToList());
        }

        /// <summary>
        /// Returns a string representation of the Android game authentication response,
        /// with sensitive values redacted.
        /// </summary>
        /// <returns>
        /// A string containing the type name and granted scopes, excluding the authorization code.
        /// </returns>
        public override string ToString()
            => $"{nameof(GamesAuthResponseAndroid)}(" +
               $"AuthorizationCode=[redacted], " +
               $"GrantedScopes=[{string.Join(", ", GrantedScopes)}])";

        /// <summary>
        /// Determines whether the specified object is equal to the current instance.
        /// </summary>
        /// <param name="obj">
        /// The object to compare with the current instance.
        /// </param>
        /// <returns>
        /// <see langword="true"/> if the specified object is a
        /// <see cref="GamesAuthResponseAndroid"/> and is equal to the current instance;
        /// otherwise, <see langword="false"/>.
        /// </returns>
        public override bool Equals(object obj)
            => Equals(obj as GamesAuthResponseAndroid);

        /// <summary>
        /// Determines whether the specified <see cref="GamesAuthResponseAndroid"/> is equal
        /// to the current instance.
        /// </summary>
        /// <param name="other">
        /// The authentication response to compare with the current instance.
        /// </param>
        /// <returns>
        /// <see langword="true"/> if both instances have the same authorization code and
        /// identical granted scopes; otherwise, <see langword="false"/>.
        /// </returns>
        public bool Equals(GamesAuthResponseAndroid other)
        {
            if (other is null)
                return false;

            if (ReferenceEquals(this, other))
                return true;

            return AuthorizationCode == other.AuthorizationCode
                && GrantedScopes.SequenceEqual(other.GrantedScopes);
        }

        /// <summary>
        /// Returns a hash code for the current instance.
        /// </summary>
        /// <returns>
        /// A hash code based on the authorization code and granted scopes.
        /// </returns>
        public override int GetHashCode()
        {
            unchecked
            {
                int hash = AuthorizationCode.GetHashCode();
                foreach (var scope in GrantedScopes)
                    hash = (hash * 397) ^ scope.GetHashCode();
                return hash;
            }
        }
    }
#endregion
}